import { RawProduct } from '@/types/commerce';

/**
 * 跨 5 大類別之高品質模擬資料庫 (Mock Data)
 * 涵蓋：耳機、手機、螢幕、電腦周邊、日本家電
 * 包含：不同變體、不同容量、不同保固、運費未知、二手/福利品、日本原裝等
 * 標註：全部皆包含 isMockData: true
 */
export const MOCK_PRODUCTS_DATA: RawProduct[] = [
  // ================= 1. 耳機 (Headphones) =================
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-SONY-XM5-BLK',
    title: '【台灣公司貨保固1年】Sony WH-1000XM5 旗艦無線降噪耳罩式耳機 (經典黑)',
    brand: 'Sony',
    model: 'WH-1000XM5',
    category: 'Headphones',
    price: 9900,
    originalPrice: 11900,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-SONY-XM5-BLK',
    condition: 'BRAND_NEW',
    sellerName: 'Sony 官方旗艦商城',
    sellerRating: 4.95,
    sellerReviewCount: 3820,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '4548736132566',
    ean: '4548736132566',
    jan: '4548736132566',
    mpn: 'WH1000XM5/B',
    rawAttributes: { color: '黑色', noiseCancelling: true, batteryHours: 30 },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-SONY-XM5-SLV',
    title: 'ソニー ワイヤレスノイズキャンセリングステレオヘッドホン WH-1000XM5 プラチナシルバー 日本国内正規品',
    brand: 'SONY',
    model: 'WH-1000XM5',
    category: 'Headphones',
    price: 36800,
    originalPrice: 42000,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-SONY-XM5-SLV',
    condition: 'BRAND_NEW',
    sellerName: 'BicCamera 日本海外旗艦店',
    sellerRating: 4.82,
    sellerReviewCount: 1420,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 1800, // 1800 JPY
    minDeliveryDays: 4,
    maxDeliveryDays: 7,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 12,
    returnPolicyDays: 14,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '4548736132573',
    ean: '4548736132573',
    jan: '4548736132573',
    mpn: 'WH1000XM5/S',
    rawAttributes: { color: '銀色', voltage: '100-240V', weight: '250g' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-SONY-XM5-USED',
    title: '【9成新福利品出清】Sony WH-1000XM5 降噪耳罩耳機 黑色 附原廠外盒配件',
    brand: 'Sony',
    model: 'WH-1000XM5',
    category: 'Headphones',
    price: 7500,
    originalPrice: 9900,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-SONY-XM5-USED',
    condition: 'OPEN_BOX',
    sellerName: '數位二手工坊',
    sellerRating: 4.60,
    sellerReviewCount: 195,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 60,
    minDeliveryDays: 2,
    maxDeliveryDays: 4,
    warrantyType: 'PARALLEL_IMPORT',
    warrantyMonths: 3,
    returnPolicyDays: 7,
    isOfficialStore: false,
    isAuthorizedSeller: false,
    stockStatus: 'LOW_STOCK',
    mpn: 'WH1000XM5/B',
    rawAttributes: { color: '黑色', conditionNote: '外盒有些微磨損，功能正常' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-BOSE-QC-ULTRA',
    title: 'Bose QuietComfort Ultra 無線消噪耳機 - 霧面黑 (台灣代理公司貨)',
    brand: 'Bose',
    model: 'QuietComfort Ultra',
    category: 'Headphones',
    price: 13500,
    originalPrice: 15800,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-BOSE-QC-ULTRA',
    condition: 'BRAND_NEW',
    sellerName: 'Bose 官方授權專賣',
    sellerRating: 4.90,
    sellerReviewCount: 980,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 15,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '017817842600',
    mpn: 'QC-ULTRA-BLK',
    rawAttributes: { color: '黑色', spatialAudio: true },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-BOSE-QC-ULTRA',
    title: 'Bose QuietComfort Ultra Headphones ワイヤレスヘッドホン ブラック 並行輸出品',
    brand: 'Bose',
    model: 'QuietComfort Ultra',
    category: 'Headphones',
    price: 49500,
    originalPrice: 59400,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-BOSE-QC-ULTRA',
    condition: 'BRAND_NEW',
    sellerName: 'Tokyo Tech Direct',
    sellerRating: 4.65,
    sellerReviewCount: 310,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 2200,
    minDeliveryDays: 5,
    maxDeliveryDays: 9,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: false,
    isAuthorizedSeller: false,
    stockStatus: 'IN_STOCK',
    mpn: 'QC-ULTRA-BLK',
    rawAttributes: { color: '黑色' },
    isMockData: true
  },

  // ================= 2. 手機 (Smartphones) =================
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-IPHONE15P-128',
    title: 'Apple iPhone 15 Pro 128GB 原色鈦金屬 台灣公司貨 (全新現貨)',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    category: 'Smartphones',
    price: 34900,
    originalPrice: 36900,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-IPHONE15P-128',
    condition: 'BRAND_NEW',
    sellerName: 'Apple 官方授權線上旗艦館',
    sellerRating: 4.98,
    sellerReviewCount: 15400,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 14,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '195949038234',
    mpn: 'MTV13TA/A',
    rawAttributes: { color: '原色鈦金屬', capacity: '128GB', sim: 'nano-SIM + eSIM' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-IPHONE15P-256',
    title: 'Apple iPhone 15 Pro 256GB 原色鈦金屬 台灣公司貨',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    category: 'Smartphones',
    price: 38400,
    originalPrice: 40400,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-IPHONE15P-256',
    condition: 'BRAND_NEW',
    sellerName: 'Apple 官方授權線上旗艦館',
    sellerRating: 4.98,
    sellerReviewCount: 12300,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 14,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '195949038296',
    mpn: 'MTV53TA/A',
    rawAttributes: { color: '原色鈦金屬', capacity: '256GB', sim: 'nano-SIM + eSIM' },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-IPHONE15P-256-SIMFREE',
    title: 'Apple iPhone 15 Pro 256GB ナチュラルチタニウム SIMフリー 日本版 (シャッター音無音可能)',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    category: 'Smartphones',
    price: 159800,
    originalPrice: 174800,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-IPHONE15P-256',
    condition: 'BRAND_NEW',
    sellerName: '秋葉原 Mobile Express',
    sellerRating: 4.75,
    sellerReviewCount: 840,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 3200, // 3200 JPY 跨境快遞
    minDeliveryDays: 3,
    maxDeliveryDays: 6,
    warrantyType: 'TAIWAN_OFFICIAL', // Apple 全球原廠保固(直營店)
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '195949038296',
    mpn: 'MTV53J/A',
    rawAttributes: { color: '原色鈦金屬', capacity: '256GB', sim: 'SIM-Free' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-S24U-256-GRY',
    title: 'SAMSUNG Galaxy S24 Ultra 5G (12G/256G) 鈦灰 - 台灣公司貨 原廠盒裝',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    category: 'Smartphones',
    price: 36900,
    originalPrice: 43900,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-S24U-256',
    condition: 'BRAND_NEW',
    sellerName: '三星品牌旗艦館',
    sellerRating: 4.92,
    sellerReviewCount: 4120,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 24, // 旗艦店兩年保固
    returnPolicyDays: 10,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '8806095300184',
    mpn: 'SM-S9280',
    rawAttributes: { color: '鈦灰', capacity: '256GB', ram: '12GB' },
    isMockData: true
  },

  // ================= 3. 螢幕 (Monitors) =================
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-DELL-U2723QE',
    title: 'DELL UltraSharp 27 4K USB-C Hub 顯示器 (U2723QE) - 原廠三年進階更換保固',
    brand: 'Dell',
    model: 'U2723QE',
    category: 'Monitors',
    price: 16888,
    originalPrice: 19999,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-DELL-U2723QE',
    condition: 'BRAND_NEW',
    sellerName: 'Dell 旗艦總代理商城',
    sellerRating: 4.88,
    sellerReviewCount: 2150,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 3,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 36, // 3 年保固
    returnPolicyDays: 7,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '5397184567223',
    mpn: 'U2723QE',
    rawAttributes: { size: '27吋', resolution: '4K UHD (3840 x 2160)', panel: 'IPS Black', usbC: '90W PD' },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-DELL-U2723QE',
    title: 'Dell U2723QE 27インチ 4K ハブモニター (IPS Black/USB-C 90W給電/RJ45/DP,HDMI) 日本正規代理店品',
    brand: 'Dell',
    model: 'U2723QE',
    category: 'Monitors',
    price: 69800,
    originalPrice: 82000,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-DELL-U2723QE',
    condition: 'BRAND_NEW',
    sellerName: 'Amazon 日本官方直營',
    sellerRating: 4.70,
    sellerReviewCount: 1680,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 5500, // 大型包裹跨境運費
    isShippingEstimated: false,
    minDeliveryDays: 6,
    maxDeliveryDays: 10,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 36,
    returnPolicyDays: 30,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '5397184567223',
    mpn: 'U2723QE',
    rawAttributes: { size: '27吋', resolution: '4K', voltage: '100-240V' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-LG-27UP850N',
    title: 'LG 27吋 4K UHD IPS 顯示器 (27UP850N-W) HDR400 / Type-C 96W',
    brand: 'LG',
    model: '27UP850N-W',
    category: 'Monitors',
    price: 11900,
    originalPrice: 14900,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-LG-27UP850N',
    condition: 'BRAND_NEW',
    sellerName: 'LG 台灣官方專賣店',
    sellerRating: 4.85,
    sellerReviewCount: 1430,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 36,
    returnPolicyDays: 7,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    mpn: '27UP850N-W',
    rawAttributes: { size: '27吋', resolution: '4K', color: '白色' },
    isMockData: true
  },

  // ================= 4. 電腦周邊 (Computer Peripherals) =================
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-LOGI-MXMASTER3S',
    title: 'Logitech 羅技 MX Master 3S 無線靜音滑鼠 - 石墨灰 (台灣繁體中文包裝/公司貨)',
    brand: 'Logitech',
    model: 'MX Master 3S',
    category: 'Peripherals',
    price: 3290,
    originalPrice: 3990,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-LOGI-MXMASTER3S',
    condition: 'BRAND_NEW',
    sellerName: '羅技官方旗艦旗艦館',
    sellerRating: 4.96,
    sellerReviewCount: 8900,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 10,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '097855175021',
    mpn: '910-006561',
    rawAttributes: { color: '石墨灰', dpi: '8000 DPI', quietClick: true },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-LOGI-MXMASTER3S-WHT',
    title: 'ロジクール MX MASTER 3S パフォーマンス ワイヤレス マウス ペイルグレー 静音 MX2300PG 日本国内正規品',
    brand: 'Logitech',
    model: 'MX Master 3S',
    category: 'Peripherals',
    price: 13800,
    originalPrice: 16940,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-LOGI-MXMASTER3S-WHT',
    condition: 'BRAND_NEW',
    sellerName: 'ヨドバシ日本海外旗艦店',
    sellerRating: 4.80,
    sellerReviewCount: 920,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 1200,
    minDeliveryDays: 4,
    maxDeliveryDays: 7,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 24, // 日本版原廠兩年保
    returnPolicyDays: 14,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '4943765057771',
    jan: '4943765057771',
    mpn: 'MX2300PG',
    rawAttributes: { color: '淺灰色', dpi: '8000 DPI' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-KEYCHRON-Q1PRO',
    title: 'Keychron Q1 Pro 無線客製化機械鍵盤 (紅軸 / 碳黑鋁合金外殼) 台灣公司貨',
    brand: 'Keychron',
    model: 'Q1 Pro',
    category: 'Peripherals',
    price: 6190,
    originalPrice: 6590,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-KEYCHRON-Q1PRO',
    condition: 'BRAND_NEW',
    sellerName: 'Keychron 台灣總代理',
    sellerRating: 4.89,
    sellerReviewCount: 1120,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 3,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    mpn: 'Q1P-M1',
    rawAttributes: { color: '碳黑色', switch: '紅軸', layout: '75%' },
    isMockData: true
  },

  // ================= 5. 日本家電 (Japanese Home Appliances) =================
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-ZOJIRUSHI-NW-PV10',
    title: '象印 圧力IH炊飯ジャー 炎舞炊き 5.5合炊き NW-PV10-BZ スレートブラック 日本製 100V',
    brand: 'Zojirushi',
    model: 'NW-PV10',
    category: 'Appliances',
    price: 49800,
    originalPrice: 62000,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-ZOJIRUSHI-NW-PV10',
    condition: 'BRAND_NEW',
    sellerName: '東京電器本舖 (海外直送專營)',
    sellerRating: 4.86,
    sellerReviewCount: 2310,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 3500, // 國際海運/空運
    minDeliveryDays: 5,
    maxDeliveryDays: 9,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    jan: '4974305224385',
    mpn: 'NW-PV10-BZ',
    rawAttributes: { capacity: '5.5合 (1.0L)', color: '黑曜石色', voltage: '100V (日本規格)', power: '1240W' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-ZOJIRUSHI-NW-PV10-PI',
    title: '【平行輸入/店家保固1年】日本象印 炎舞炊き NW-PV10 壓力IH電子鍋 5.5人份 黑色 (110V可相容)',
    brand: 'Zojirushi',
    model: 'NW-PV10',
    category: 'Appliances',
    price: 15800,
    originalPrice: 18500,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-ZOJIRUSHI-NW-PV10',
    condition: 'BRAND_NEW',
    sellerName: '日本生活代購館',
    sellerRating: 4.72,
    sellerReviewCount: 520,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 150,
    minDeliveryDays: 2,
    maxDeliveryDays: 4,
    warrantyType: 'PARALLEL_IMPORT',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: false,
    isAuthorizedSeller: false,
    stockStatus: 'IN_STOCK',
    mpn: 'NW-PV10-BZ',
    rawAttributes: { capacity: '5.5人份', color: '黑色', voltage: '100V' },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-PANASONIC-NA-LX129C',
    title: 'Panasonic ななめドラム洗濯乾燥機 NA-LX129CL マットホワイト (大型家電/送料別途見積もり)',
    brand: 'Panasonic',
    model: 'NA-LX129CL',
    category: 'Appliances',
    price: 285000,
    originalPrice: 320000,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-PANASONIC-NA-LX129C',
    condition: 'BRAND_NEW',
    sellerName: 'Japan Heavy Logistics',
    sellerRating: 4.50,
    sellerReviewCount: 88,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 0, // 運費未知，顯示未完整估算
    isShippingEstimated: true,
    minDeliveryDays: 14,
    maxDeliveryDays: 25,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 12,
    returnPolicyDays: 0,
    isOfficialStore: false,
    isAuthorizedSeller: false,
    stockStatus: 'IN_STOCK',
    jan: '4549980724859',
    mpn: 'NA-LX129CL-W',
    rawAttributes: { capacity: '洗濯12kg / 乾燥6kg', color: '消光白', voltage: '100V', isHeavyItem: true },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-DYSON-AIRSTRAIT',
    title: 'Dyson Airstrait ストレイトナー ウェットトゥードライ ドライヤー ヘアアイロン 日本正規品',
    brand: 'Dyson',
    model: 'Airstrait',
    category: 'Appliances',
    price: 49800,
    originalPrice: 53800,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-DYSON-AIRSTRAIT',
    condition: 'BRAND_NEW',
    sellerName: '銀座家電 Outlet',
    sellerRating: 4.78,
    sellerReviewCount: 460,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 2100,
    minDeliveryDays: 4,
    maxDeliveryDays: 8,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 24,
    returnPolicyDays: 14,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    mpn: 'HT01',
    rawAttributes: { color: '普魯士藍/銅色', voltage: '100V 專用' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-DYSON-AIRSTRAIT-OFFICIAL',
    title: '【Dyson 戴森 官方旗艦店】Dyson Airstrait 二合一吹風直髮器 普魯士藍 (台灣電壓公司貨 2年保固)',
    brand: 'Dyson',
    model: 'Airstrait',
    category: 'Appliances',
    price: 16600,
    originalPrice: 17600,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-DYSON-AIRSTRAIT-TW',
    condition: 'BRAND_NEW',
    sellerName: 'Dyson 戴森官方授權旗艦店',
    sellerRating: 4.95,
    sellerReviewCount: 3500,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 24,
    returnPolicyDays: 15,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    gtin: '5025155088210',
    mpn: 'HT01-TW',
    rawAttributes: { color: '普魯士藍', voltage: '110V 台灣專用' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-APPLE-WATCH-S9-41',
    title: 'Apple Watch Series 9 GPS 41mm 星光色鋁金屬錶殼搭配星光色運動型錶帶',
    brand: 'Apple',
    model: 'Watch Series 9',
    category: 'Smartphones',
    price: 11900,
    originalPrice: 13500,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-AW-S9-41',
    condition: 'BRAND_NEW',
    sellerName: 'Studio A 官方授權專賣',
    sellerRating: 4.92,
    sellerReviewCount: 2840,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    mpn: 'MR8T3TA/A',
    rawAttributes: { size: '41mm', color: '星光色', connection: 'GPS' },
    isMockData: true
  },
  {
    source: 'mock_tw_store',
    sourceProductId: 'TW-APPLE-WATCH-S9-45',
    title: 'Apple Watch Series 9 GPS 45mm 午夜色鋁金屬錶殼搭配午夜色運動型錶帶',
    brand: 'Apple',
    model: 'Watch Series 9',
    category: 'Smartphones',
    price: 12900,
    originalPrice: 14500,
    currency: 'TWD',
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600',
    productUrl: 'https://tw-mall.example.com/p/TW-AW-S9-45',
    condition: 'BRAND_NEW',
    sellerName: 'Studio A 官方授權專賣',
    sellerRating: 4.92,
    sellerReviewCount: 3120,
    shipsToTaiwan: true,
    countryOfOrigin: 'TW',
    shippingFee: 0,
    minDeliveryDays: 1,
    maxDeliveryDays: 2,
    warrantyType: 'TAIWAN_OFFICIAL',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: true,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    mpn: 'MR993TA/A',
    rawAttributes: { size: '45mm', color: '午夜色', connection: 'GPS' },
    isMockData: true
  },
  {
    source: 'mock_jp_store',
    sourceProductId: 'JP-SHARP-KI-RX75',
    title: 'SHARP 加湿空気清浄機 プラズマクラスター NEXT (50000) KI-RX75-W プレミアムホワイト 100V 日本製',
    brand: 'Sharp',
    model: 'KI-RX75',
    category: 'Appliances',
    price: 52800,
    originalPrice: 65000,
    currency: 'JPY',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600',
    productUrl: 'https://jp-direct.example.com/p/JP-SHARP-KI-RX75',
    condition: 'BRAND_NEW',
    sellerName: '大阪電器直販',
    sellerRating: 4.74,
    sellerReviewCount: 680,
    shipsToTaiwan: true,
    countryOfOrigin: 'JP',
    shippingFee: 4200,
    minDeliveryDays: 6,
    maxDeliveryDays: 10,
    warrantyType: 'ORIGIN_DOMESTIC',
    warrantyMonths: 12,
    returnPolicyDays: 7,
    isOfficialStore: false,
    isAuthorizedSeller: true,
    stockStatus: 'IN_STOCK',
    jan: '4974019223360',
    mpn: 'KI-RX75-W',
    rawAttributes: { color: '白', voltage: '100V', area: '適用約34畳' },
    isMockData: true
  }
];
